name: pkg releases
on:
  push:
    branches-ignore:
      - latest
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Tags
        id: tags
        uses: livepeer/action-gh-release-tags@v0

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: build pkgs
        # I want to do --parallel here, but the binary downloads conflict with each other
        run: |
          yarn run lerna-run pkg

      - name: move pkgs
        run: |
          mkdir -p ./pkg-releases
          for package in api www; do
            for arch in linux-arm64 linux-x64 macos-arm64 macos-x64 win-x64; do
              inName="$package-$arch"
              outName="livepeer-$package"
              archiveName="livepeer-$(echo $inName | sed -e 's/x64/amd64/;s/win/windows/;s/macos/darwin/').tar.gz"
              if [[ "$arch" == "win-x64" ]]; then
                inName="$inName.exe"
                outName="$outName.exe"
              fi
              cd ./packages/$package/bin
              mv ./$inName ./$outName
              tar -czvf ../../../pkg-releases/$archiveName ./$outName
              cd -
            done
          done

      - name: archive livepeer-api-darwin-arm64.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: livepeer-api-darwin-arm64.tar.gz
          path: |
            ./pkg-releases/livepeer-api-darwin-arm64.tar.gz

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Add binaries to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./pkg-releases/livepeer-api-linux-arm64.tar.gz
            ./pkg-releases/livepeer-api-linux-amd64.tar.gz
            ./pkg-releases/livepeer-api-darwin-arm64.tar.gz
            ./pkg-releases/livepeer-api-darwin-amd64.tar.gz
            ./pkg-releases/livepeer-api-windows-amd64.tar.gz
            ./pkg-releases/livepeer-www-linux-arm64.tar.gz
            ./pkg-releases/livepeer-www-linux-amd64.tar.gz
            ./pkg-releases/livepeer-www-darwin-arm64.tar.gz
            ./pkg-releases/livepeer-www-darwin-amd64.tar.gz
            ./pkg-releases/livepeer-www-windows-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
